## **Traffic Crash Analysis and Safety Intelligence Platform**

In [1]:
import pandas as pd
import mysql.connector

In [2]:
connection = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "12345678",
    database = "crash_record_db"
)

cursor = connection.cursor()
cursor
print("I am Conneted to mysql")

I am Conneted to mysql

In [3]:
df = pd.read_csv("Traffic_CrashesData.csv")
df.head(3)

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date,year
0,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...,01/14/2025 12:25:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,2.0,0.0,12,3,1,41.997808,-87.655770,POINT (-87.655770494712 41.997807727633),2025-01-14 12:25:00,2025
1,027b0b4c21460d3441fd83929abb9673c6fc0c7d575675...,05/23/2025 09:30:00 AM,30,STOP SIGN/FLASHER,UNKNOWN,UNKNOWN,DAYLIGHT,TURNING,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,2.0,0.0,9,6,5,41.946529,-87.688106,POINT (-87.688106391039 41.946529480518),2025-05-23 09:30:00,2025
2,04d91dffc94f677358ca47056921ba5c4224320df27ed4...,04/05/2025 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,UNKNOWN,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,20,7,4,41.899325,-87.715074,POINT (-87.715074373867 41.899324573751),2025-04-05 20:00:00,2025

In [4]:
print(df.keys())

Index(['CRASH_RECORD_ID', 'CRASH_DATE', 'POSTED_SPEED_LIMIT',
       'TRAFFIC_CONTROL_DEVICE', 'DEVICE_CONDITION', 'WEATHER_CONDITION',
       'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE',
       'ALIGNMENT', 'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'REPORT_TYPE',
       'CRASH_TYPE', 'DAMAGE', 'DATE_POLICE_NOTIFIED',
       'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO',
       'STREET_DIRECTION', 'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'NUM_UNITS',
       'MOST_SEVERE_INJURY', 'INJURIES_TOTAL', 'INJURIES_FATAL',
       'INJURIES_INCAPACITATING', 'INJURIES_NON_INCAPACITATING',
       'INJURIES_REPORTED_NOT_EVIDENT', 'INJURIES_NO_INDICATION',
       'INJURIES_UNKNOWN', 'CRASH_HOUR', 'CRASH_DAY_OF_WEEK', 'CRASH_MONTH',
       'LATITUDE', 'LONGITUDE', 'LOCATION', 'date', 'year'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660934 entries, 0 to 660933
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH_RECORD_ID                660934 non-null  object
 1   CRASH_DATE                     660934 non-null  object
 2   POSTED_SPEED_LIMIT             660934 non-null  int64
 3   TRAFFIC_CONTROL_DEVICE         660934 non-null  object
 4   DEVICE_CONDITION               660934 non-null  object
 5   WEATHER_CONDITION              660934 non-null  object
 6   LIGHTING_CONDITION             660934 non-null  object
 7   FIRST_CRASH_TYPE               660934 non-null  object
 8   TRAFFICWAY_TYPE                660934 non-null  object
 9   ALIGNMENT                      660934 non-null  object
 10  ROADWAY_SURFACE_COND           660934 non-null  object
 11  ROAD_DEFECT                    660934 non-null  object
 12  REPORT_TYPE                    660934 non-null  object
 13  CRASH_TYPE                     660934 non-null  object
 14  DAMAGE                         660934 non-null  object
 15  DATE_POLICE_NOTIFIED           660934 non-null  object
 16  PRIM_CONTRIBUTORY_CAUSE        660934 non-null  object
 17  SEC_CONTRIBUTORY_CAUSE         660934 non-null  object
 18  STREET_NO                      660934 non-null  int64
 19  STREET_DIRECTION               660934 non-null  object
 20  STREET_NAME                    660934 non-null  object
 21  BEAT_OF_OCCURRENCE             660934 non-null  float64
 22  NUM_UNITS                      660934 non-null  int64
 23  MOST_SEVERE_INJURY             660934 non-null  object
 24  INJURIES_TOTAL                 660934 non-null  float64
 25  INJURIES_FATAL                 660934 non-null  float64
 26  INJURIES_INCAPACITATING        660934 non-null  float64
 27  INJURIES_NON_INCAPACITATING    660934 non-null  float64
 28  INJURIES_REPORTED_NOT_EVIDENT  660934 non-null  float64
 29  INJURIES_NO_INDICATION         660934 non-null  float64
 30  INJURIES_UNKNOWN               660934 non-null  float64
 31  CRASH_HOUR                     660934 non-null  int64
 32  CRASH_DAY_OF_WEEK              660934 non-null  int64
 33  CRASH_MONTH                    660934 non-null  int64
 34  LATITUDE                       660934 non-null  float64
 35  LONGITUDE                      660934 non-null  float64
 36  LOCATION                       660934 non-null  object
 37  date                           660934 non-null  object
 38  year                           660934 non-null  int64
dtypes: float64(10), int64(7), object(22)
memory usage: 196.7+ MB

In [6]:
df.isnull().sum()

CRASH_RECORD_ID                  0
CRASH_DATE                       0
POSTED_SPEED_LIMIT               0
TRAFFIC_CONTROL_DEVICE           0
DEVICE_CONDITION                 0
WEATHER_CONDITION                0
LIGHTING_CONDITION               0
FIRST_CRASH_TYPE                 0
TRAFFICWAY_TYPE                  0
ALIGNMENT                        0
ROADWAY_SURFACE_COND             0
ROAD_DEFECT                      0
REPORT_TYPE                      0
CRASH_TYPE                       0
DAMAGE                           0
DATE_POLICE_NOTIFIED             0
PRIM_CONTRIBUTORY_CAUSE          0
SEC_CONTRIBUTORY_CAUSE           0
STREET_NO                        0
STREET_DIRECTION                 0
STREET_NAME                      0
BEAT_OF_OCCURRENCE               0
NUM_UNITS                        0
MOST_SEVERE_INJURY               0
INJURIES_TOTAL                   0
INJURIES_FATAL                   0
INJURIES_INCAPACITATING          0
INJURIES_NON_INCAPACITATING      0
INJURIES_REPORTED_NOT_EVIDENT    0
INJURIES_NO_INDICATION           0
INJURIES_UNKNOWN                 0
CRASH_HOUR                       0
CRASH_DAY_OF_WEEK                0
CRASH_MONTH                      0
LATITUDE                         0
LONGITUDE                        0
LOCATION                         0
date                             0
year                             0
dtype: int64

In [6]:
from sqlalchemy import create_engine # This library will help us import the CSV data to the workbench

engine = create_engine("mysql+pymysql://root:12345678@localhost:3306/crash_record_db")

df.to_sql(
    name="traffic_crashesdata", # This is my table name
    con=engine, # This pushes the CSV data(df) to engine(mysql--->car_crash---->traffic_crashesdata)
    if_exists="replace",  # append will keep on add the data(which increase their count) to the table while replace will not
    index=False
    )

660934

SELECT   → Choose the columns
  |
FROM     → Choose from the Table
  |
WHERE    → Filter the rows(specific)
  |
GROUP BY → Group data
  |
HAVING   → Filter grouped data
  |
ORDER BY → Sort results
  |
LIMIT    → show the data as per the limit num

### __Phase 1__

In [7]:
### Row Number

query = """
SELECT
    COUNT(*) AS total_rows
FROM
    traffic_crashesdata
"""

cursor.execute(query)
res = cursor.fetchall()

print(res)
print(df.shape)

[(660934,)]
(660934, 39)

In [8]:
### Describe the Data Type

from tabulate import tabulate

query = """
DESCRIBE traffic_crashesdata
"""

cursor.execute(query)
res = cursor.fetchall()

data = [(col[0], col[1]) for col in res]

print(tabulate(data, headers=["Column", "Data Type"], tablefmt="grid"))

+-------------------------------+-------------+
| Column                        | Data Type   |
+===============================+=============+
| CRASH_RECORD_ID               | text        |
+-------------------------------+-------------+
| CRASH_DATE                    | text        |
+-------------------------------+-------------+
| POSTED_SPEED_LIMIT            | bigint      |
+-------------------------------+-------------+
| TRAFFIC_CONTROL_DEVICE        | text        |
+-------------------------------+-------------+
| DEVICE_CONDITION              | text        |
+-------------------------------+-------------+
| WEATHER_CONDITION             | text        |
+-------------------------------+-------------+
| LIGHTING_CONDITION            | text        |
+-------------------------------+-------------+
| FIRST_CRASH_TYPE              | text        |
+-------------------------------+-------------+
| TRAFFICWAY_TYPE               | text        |
+-------------------------------+-------------+
| ALIGNMENT                     | text        |
+-------------------------------+-------------+
| ROADWAY_SURFACE_COND          | text        |
+-------------------------------+-------------+
| ROAD_DEFECT                   | text        |
+-------------------------------+-------------+
| REPORT_TYPE                   | text        |
+-------------------------------+-------------+
| CRASH_TYPE                    | text        |
+-------------------------------+-------------+
| DAMAGE                        | text        |
+-------------------------------+-------------+
| DATE_POLICE_NOTIFIED          | text        |
+-------------------------------+-------------+
| PRIM_CONTRIBUTORY_CAUSE       | text        |
+-------------------------------+-------------+
| SEC_CONTRIBUTORY_CAUSE        | text        |
+-------------------------------+-------------+
| STREET_NO                     | bigint      |
+-------------------------------+-------------+
| STREET_DIRECTION              | text        |
+-------------------------------+-------------+
| STREET_NAME                   | text        |
+-------------------------------+-------------+
| BEAT_OF_OCCURRENCE            | double      |
+-------------------------------+-------------+
| NUM_UNITS                     | bigint      |
+-------------------------------+-------------+
| MOST_SEVERE_INJURY            | text        |
+-------------------------------+-------------+
| INJURIES_TOTAL                | double      |
+-------------------------------+-------------+
| INJURIES_FATAL                | double      |
+-------------------------------+-------------+
| INJURIES_INCAPACITATING       | double      |
+-------------------------------+-------------+
| INJURIES_NON_INCAPACITATING   | double      |
+-------------------------------+-------------+
| INJURIES_REPORTED_NOT_EVIDENT | double      |
+-------------------------------+-------------+
| INJURIES_NO_INDICATION        | double      |
+-------------------------------+-------------+
| INJURIES_UNKNOWN              | double      |
+-------------------------------+-------------+
| CRASH_HOUR                    | bigint      |
+-------------------------------+-------------+
| CRASH_DAY_OF_WEEK             | bigint      |
+-------------------------------+-------------+
| CRASH_MONTH                   | bigint      |
+-------------------------------+-------------+
| LATITUDE                      | double      |
+-------------------------------+-------------+
| LONGITUDE                     | double      |
+-------------------------------+-------------+
| LOCATION                      | text        |
+-------------------------------+-------------+
| date                          | text        |
+-------------------------------+-------------+
| year                          | bigint      |
+-------------------------------+-------------+

### __Phase 2__

#### __Crash_Distribution__

In [9]:
# Distribution of Crashes

query = """
SELECT
    crash_type,
    COUNT(*) AS crash_counts
FROM
    traffic_crashesdata
GROUP BY
    crash_type
ORDER BY
    crash_counts DESC
"""

df1 = pd.read_sql(query, engine)
df1

# carsh count of NO Injury > Injury

                         crash_type  crash_counts
0            NO INJURY / DRIVE AWAY        465793
1  INJURY AND / OR TOW DUE TO CRASH        195141

#### __Distibution of crashes by comman causes__

In [10]:
# weather condition

query = """
SELECT
    weather_condition,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    weather_condition
ORDER BY
    crash_count DESC
"""

df1 = pd.read_sql(query, engine)
df1

           weather_condition  crash_count
0                      CLEAR       515540
1                       RAIN        51207
2                    UNKNOWN        46958
3                       SNOW        21732
4            CLOUDY/OVERCAST        18883
5      FREEZING RAIN/DRIZZLE         2300
6                      OTHER         2199
7             FOG/SMOKE/HAZE          797
8                 SLEET/HAIL          623
9               BLOWING SNOW          583
10    SEVERE CROSS WIND GATE           90
11  BLOWING SAND, SOIL, DIRT           22

In [11]:
# Lighting_condiiton

query = """
SELECT
    lighting_condition,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    lighting_condition
ORDER BY
    crash_count DESC
"""

df3 = pd.read_sql(query,engine)
df3

       lighting_condition  crash_count
0                DAYLIGHT       416853
1  DARKNESS, LIGHTED ROAD       148474
2                 UNKNOWN        37861
3                DARKNESS        29384
4                    DUSK        17647
5                    DAWN        10715

In [12]:
# Primary_Contributary_Cause

query = """
SELECT
    prim_contributory_cause,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    prim_contributory_cause
ORDER BY
    crash_count DESC
"""

df4 = pd.read_sql(query, engine)
df4

                              prim_contributory_cause  crash_count
0                                 UNABLE TO DETERMINE       272768
1                       FAILING TO YIELD RIGHT-OF-WAY        73413
2                               FOLLOWING TOO CLOSELY        57046
3                         IMPROPER OVERTAKING/PASSING        33919
4                                      NOT APPLICABLE        33214
5              FAILING TO REDUCE SPEED TO AVOID CRASH        28235
6                 DRIVING SKILLS/KNOWLEDGE/EXPERIENCE        24298
7                          IMPROPER TURNING/NO SIGNAL        22027
8                                    IMPROPER BACKING        21763
9                                 IMPROPER LANE USAGE        21141
10                       DISREGARDING TRAFFIC SIGNALS        14042
11                                            WEATHER         9479
12  OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELE...         8192
13                             DISREGARDING STOP SIGN         6839
14                  DISTRACTION - FROM INSIDE VEHICLE         4144
15                      EQUIPMENT - VEHICLE CONDITION         4111
16                    DRIVING ON WRONG SIDE/WRONG WAY         4110
17                       PHYSICAL CONDITION OF DRIVER         3912
18  VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS,...         3625
19  UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN...         2970
20                 DISTRACTION - FROM OUTSIDE VEHICLE         2349
21                   DISREGARDING OTHER TRAFFIC SIGNS         1383
22  EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST         1140
23           ROAD ENGINEERING/SURFACE/MARKING DEFECTS         1127
24                      ROAD CONSTRUCTION/MAINTENANCE         1026
25                  CELL PHONE USE OTHER THAN TEXTING          797
26                         DISREGARDING ROAD MARKINGS          713
27    HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)          586
28                                             ANIMAL          580
29                               TURNING RIGHT ON RED          544
30                                RELATED TO BUS STOP          523
31  DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGAT...          330
32                                            TEXTING          197
33                            DISREGARDING YIELD SIGN          165
34                              OBSTRUCTED CROSSWALKS          110
35                         PASSING STOPPED SCHOOL BUS           75
36             BICYCLE ADVANCING LEGALLY ON RED LIGHT           33
37          MOTORCYCLE ADVANCING LEGALLY ON RED LIGHT            8

In [13]:
# Road_surface_Condition

query = """
SELECT
    roadway_surface_cond,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    roadway_surface_cond
ORDER BY
    crash_count DESC
"""

df4 = pd.read_sql(query, engine)
df4

  roadway_surface_cond  crash_count
0                  DRY       478544
1                  WET        78820
2              UNKNOWN        75329
3        SNOW OR SLUSH        21648
4                  ICE         4547
5                OTHER         1869
6      SAND, MUD, DIRT          177

### __Time Based Trend__

In [ ]:
#Crash_per_hours

query = """
SELECT
    crash_hour,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    crash_hour
ORDER BY
    crash_count DESC
"""

df5 = pd.read_sql(query, engine)
df5

    crash_hour  crash_count
0           15        51919
1           16        50650
2           17        48389
3           14        44049
4           18        39806
5           13        39555
6           12        38473
7            8        34288
8           11        33557
9           19        29887
10          10        29818
11           9        29310
12           7        26959
13          20        24797
14          21        22047
15          22        20018
16          23        18032
17           0        15481
18           6        13491
19           1        13257
20           2        11107
21           3         9190
22           5         8987
23           4         7867

In [16]:
# crashes_per_day

query = """
SELECT
    crash_date,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    crash_date
ORDER BY
    crash_count DESC
"""

df6 = pd.read_sql(query, engine)
df6

                    crash_date  crash_count
0       02/06/2025 08:00:00 AM           37
1       01/14/2026 08:30:00 AM           31
2       01/14/2026 08:00:00 AM           31
3       01/14/2026 09:00:00 AM           30
4       12/29/2020 05:00:00 PM           30
...                        ...          ...
446231  10/30/2022 05:23:00 PM            1
446232  07/09/2020 11:32:00 PM            1
446233  07/15/2021 07:56:00 AM            1
446234  11/28/2022 01:10:00 AM            1
446235  06/15/2024 08:22:00 PM            1

[446236 rows x 2 columns]

In [17]:
# crashes_per_week (day of week)

query = """
SELECT
    crash_day_of_week,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    crash_day_of_week
ORDER BY
    crash_count DESC;
"""

df7 = pd.read_sql(query, engine)
df7

   crash_day_of_week  crash_count
0                  6       106924
1                  7        97636
2                  5        95453
3                  4        94278
4                  3        92935
5                  2        89408
6                  1        84300

In [ ]:
# crashes_per_month

query = """
select 
    crash_month, 
    count(*) as crash_count 
from 
    traffic_crashesdata
group by crash_month
order by crash_count desc;"""

df8 = pd.read_sql(query, engine)
df8

    crash_month  crash_count
0             8        57790
1             1        57398
2             3        57391
3            10        57064
4             6        56971
5             7        56742
6             5        56544
7             2        56327
8             9        55805
9            12        50752
10           11        50262
11            4        47888

In [18]:
# crashes_per_year
 
query = """
SELECT
    year,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    year
ORDER BY
    crash_count DESC;
"""

df9 = pd.read_sql(query, engine)
df9

   year  crash_count
0  2024       110853
1  2023       109714
2  2025       107965
3  2021       107937
4  2022       107462
5  2020        91509
6  2026        25494

### __Phase 3__

#### __Find the top 5 most dangerous combinations of weather and crash type based on total crashes__

In [19]:
query = """
SELECT
    weather_condition,
    crash_type,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
GROUP BY
    weather_condition,
    crash_type
ORDER BY
    crash_count DESC
LIMIT 5
"""

df10 = pd.read_sql(query, engine)
df10

  weather_condition                        crash_type  crash_count
0             CLEAR            NO INJURY / DRIVE AWAY       360238
1             CLEAR  INJURY AND / OR TOW DUE TO CRASH       155302
2           UNKNOWN            NO INJURY / DRIVE AWAY        41442
3              RAIN            NO INJURY / DRIVE AWAY        31560
4              RAIN  INJURY AND / OR TOW DUE TO CRASH        19647

#### __Identify the top 10 streets with the highest number of injury crashes__

In [20]:
query = """
SELECT
    street_name,
    crash_type,
    COUNT(*) AS crash_count
FROM
    traffic_crashesdata
WHERE
    crash_type = 'INJURY AND / OR TOW DUE TO CRASH'
GROUP BY
    street_name,
    crash_type
ORDER BY
    crash_count DESC
LIMIT 10
"""

df11 = pd.read_sql(query, engine)
df11

        street_name                        crash_type  crash_count
0       WESTERN AVE  INJURY AND / OR TOW DUE TO CRASH         5334
1        PULASKI RD  INJURY AND / OR TOW DUE TO CRASH         4899
2        CICERO AVE  INJURY AND / OR TOW DUE TO CRASH         4515
3       ASHLAND AVE  INJURY AND / OR TOW DUE TO CRASH         4368
4        HALSTED ST  INJURY AND / OR TOW DUE TO CRASH         4124
5        KEDZIE AVE  INJURY AND / OR TOW DUE TO CRASH         3539
6  LAKE SHORE DR SB  INJURY AND / OR TOW DUE TO CRASH         2449
7  LAKE SHORE DR NB  INJURY AND / OR TOW DUE TO CRASH         2314
8  STONY ISLAND AVE  INJURY AND / OR TOW DUE TO CRASH         2252
9          STATE ST  INJURY AND / OR TOW DUE TO CRASH         2231

#### __Find the percentage of crashes that resulted in injuries for each crash type__

In [111]:
df["CRASH_TYPE"].unique()
df["INJURIES_TOTAL"].unique()

array([ 0.,  1.,  2.,  3.,  5.,  6.,  4.,  7., 11.,  8.,  9., 19., 10.,
       17., 15., 12., 14., 13., 21., 16.])

In [21]:
query = """
SELECT
    crash_type,
    COUNT(*) AS occurrence,
    SUM(CASE
        WHEN crash_type = 'INJURY AND / OR TOW DUE TO CRASH'
        THEN 1
        ELSE 0
    END) AS crash_count,
    (SUM(CASE
        WHEN crash_type = 'INJURY AND / OR TOW DUE TO CRASH'
        THEN 1
        ELSE 0
    END) * 100.0 / COUNT(*)) AS crash_percentage
FROM
    traffic_crashesdata
GROUP BY
    crash_type
ORDER BY
    crash_percentage;
"""

df12 = pd.read_sql(query, engine)
df12

                         crash_type  occurrence  crash_count  crash_percentage
0            NO INJURY / DRIVE AWAY      465793          0.0               0.0
1  INJURY AND / OR TOW DUE TO CRASH      195141     195141.0             100.0

#### __Find the top 5 primary causes of crashes during night time (CRASH_HOUR ≥ 18)__

In [23]:
query = """
SELECT
    PRIM_CONTRIBUTORY_CAUSE,
    CRASH_HOUR AS Time,
    COUNT(*) AS Total_Crashes
FROM
    traffic_crashesdata
WHERE
    CRASH_HOUR >= 18
GROUP BY
    PRIM_CONTRIBUTORY_CAUSE,
    CRASH_HOUR
ORDER BY
    Total_Crashes DESC
LIMIT 5
"""

df13 = pd.read_sql(query,engine)
df13

  PRIM_CONTRIBUTORY_CAUSE  Time  Total_Crashes
0     UNABLE TO DETERMINE    18          15916
1     UNABLE TO DETERMINE    19          11973
2     UNABLE TO DETERMINE    20          10208
3     UNABLE TO DETERMINE    21           9208
4     UNABLE TO DETERMINE    22           8608

#### __Compare average number of injuries in daylight vs darkness conditions__

In [ ]:
# avg = sum(condition)/total

In [24]:
df["LIGHTING_CONDITION"].value_counts()

LIGHTING_CONDITION
DAYLIGHT                  416853
DARKNESS, LIGHTED ROAD    148474
UNKNOWN                    37861
DARKNESS                   29384
DUSK                       17647
DAWN                       10715
Name: count, dtype: int64

In [25]:
query = """
SELECT
    LIGHTING_CONDITION,
    AVG(INJURIES_TOTAL) AS AVG_INJURIES
FROM
    TRAFFIC_CRASHESDATA
WHERE
    LIGHTING_CONDITION IN ('DAYLIGHT', 'DARKNESS')
GROUP BY
    LIGHTING_CONDITION
"""

df14 = pd.read_sql(query,engine)
df14

  LIGHTING_CONDITION  AVG_INJURIES
0           DAYLIGHT      0.207054
1           DARKNESS      0.216853

#### __Find which traffic control device type has the highest average injuries per crash__

In [ ]:
# AVG = SUM(INJURIES_TOTAL) / COUNT(INJURIES_TOTAL)

In [26]:
df["TRAFFIC_CONTROL_DEVICE"].value_counts()

TRAFFIC_CONTROL_DEVICE
NO CONTROLS                 365441
TRAFFIC SIGNAL              183021
STOP SIGN/FLASHER            66791
UNKNOWN                      35844
OTHER                         4717
YIELD                         1068
OTHER REG. SIGN                871
PEDESTRIAN CROSSING SIGN       751
OTHER WARNING SIGN             444
FLASHING CONTROL SIGNAL        417
RAILROAD CROSSING GATE         409
SCHOOL ZONE                    272
DELINEATORS                    269
RR CROSSING SIGN               221
POLICE/FLAGMAN                 182
OTHER RAILROAD CROSSING        130
NO PASSING                      57
BICYCLE CROSSING SIGN           29
Name: count, dtype: int64

In [27]:
query = """
SELECT
    TRAFFIC_CONTROL_DEVICE,
    AVG(INJURIES_TOTAL) AS AVG_INJURIES,
    COUNT(*) AS CRASH_COUNT
FROM
    TRAFFIC_CRASHESDATA
GROUP BY
    TRAFFIC_CONTROL_DEVICE
ORDER BY
    AVG_INJURIES DESC
"""

df15 = pd.read_sql(query,engine)
df15

      TRAFFIC_CONTROL_DEVICE  AVG_INJURIES  CRASH_COUNT
0      BICYCLE CROSSING SIGN      0.655172           29
1   PEDESTRIAN CROSSING SIGN      0.623169          751
2    FLASHING CONTROL SIGNAL      0.446043          417
3                      YIELD      0.352060         1068
4                 NO PASSING      0.350877           57
5          STOP SIGN/FLASHER      0.336782        66791
6             TRAFFIC SIGNAL      0.312511       183021
7    OTHER RAILROAD CROSSING      0.307692          130
8                DELINEATORS      0.297398          269
9             POLICE/FLAGMAN      0.274725          182
10               SCHOOL ZONE      0.272059          272
11    RAILROAD CROSSING GATE      0.256724          409
12                     OTHER      0.233835         4717
13        OTHER WARNING SIGN      0.202703          444
14          RR CROSSING SIGN      0.180995          221
15           OTHER REG. SIGN      0.166475          871
16               NO CONTROLS      0.156832       365441
17                   UNKNOWN      0.124289        35844

#### __Identify the top 5 locations (latitude/longitude) with the highest crash frequency__

In [30]:
query = """
SELECT
    LATITUDE,
    LONGITUDE,
    COUNT(*) AS CRASH_FREQ_COUNT
FROM
    TRAFFIC_CRASHESDATA
GROUP BY
    LATITUDE,
    LONGITUDE
ORDER BY
    CRASH_FREQ_COUNT DESC
LIMIT 5
"""

df16 = pd.read_sql(query,engine)
df16

    LATITUDE  LONGITUDE  CRASH_FREQ_COUNT
0  41.976201 -87.905309              1247
1  41.900959 -87.619928               661
2  41.791420 -87.580148               473
3  41.751461 -87.585972               469
4  41.722257 -87.585276               353

#### __Find the top 5 streets with the highest injury rate, considering only streets with more than 100 crashes__

In [31]:
query = """
SELECT
    STREET_NAME,
    AVG(INJURIES_TOTAL) AS INJURY_RATE,
    COUNT(*) AS CRASH_COUNT
FROM
    TRAFFIC_CRASHESDATA
GROUP BY
    STREET_NAME
HAVING
    COUNT(*) > 100
ORDER BY
    INJURY_RATE DESC
LIMIT 5
"""

df17 = pd.read_sql(query,engine)
df17

         STREET_NAME  INJURY_RATE  CRASH_COUNT
0       MARQUETTE DR     0.450185          271
1          FIFTH AVE     0.434783          299
2        CORCORAN PL     0.401639          122
3  SOUTH CHICAGO AVE     0.388304         1710
4       DOUGLAS BLVD     0.387179          390

#### __For each year, identify the most common crash type__

In [35]:
query = """
SELECT
    YEAR,
    CRASH_TYPE,
    COUNT(*) AS CRASH_COUNT
FROM
    TRAFFIC_CRASHESDATA
GROUP BY
    YEAR,
    CRASH_TYPE
ORDER BY
    YEAR,
    CRASH_COUNT DESC
"""

df18 = pd.read_sql(query,engine)
df18

    YEAR                        CRASH_TYPE  CRASH_COUNT
0   2020            NO INJURY / DRIVE AWAY        62706
1   2020  INJURY AND / OR TOW DUE TO CRASH        28803
2   2021            NO INJURY / DRIVE AWAY        74661
3   2021  INJURY AND / OR TOW DUE TO CRASH        33276
4   2022            NO INJURY / DRIVE AWAY        75897
5   2022  INJURY AND / OR TOW DUE TO CRASH        31565
6   2023            NO INJURY / DRIVE AWAY        78034
7   2023  INJURY AND / OR TOW DUE TO CRASH        31680
8   2024            NO INJURY / DRIVE AWAY        78560
9   2024  INJURY AND / OR TOW DUE TO CRASH        32293
10  2025            NO INJURY / DRIVE AWAY        77388
11  2025  INJURY AND / OR TOW DUE TO CRASH        30577
12  2026            NO INJURY / DRIVE AWAY        18547
13  2026  INJURY AND / OR TOW DUE TO CRASH         6947

In [37]:
query = """
SELECT
    YEAR,
    CRASH_TYPE,
    CRASH_COUNT
FROM (
    SELECT
        YEAR,
        CRASH_TYPE,
        COUNT(*) AS CRASH_COUNT,
        ROW_NUMBER() OVER (PARTITION BY YEAR ORDER BY COUNT(*) DESC) AS rn
    FROM
        TRAFFIC_CRASHESDATA
    GROUP BY
        YEAR,
        CRASH_TYPE ) temprory
WHERE rn = 1
"""

df18 = pd.read_sql(query, engine)
df18

## ROW_NUMBER() try to assign each row a position number(desc order) ex: 2020 no_injury(rn=1) injury(rn=2)...2021 no_injury(rn=1) injury(rn=2)
## PARTION BY Split the data into invidual group(here year)

   YEAR              CRASH_TYPE  CRASH_COUNT
0  2020  NO INJURY / DRIVE AWAY        62706
1  2021  NO INJURY / DRIVE AWAY        74661
2  2022  NO INJURY / DRIVE AWAY        75897
3  2023  NO INJURY / DRIVE AWAY        78034
4  2024  NO INJURY / DRIVE AWAY        78560
5  2025  NO INJURY / DRIVE AWAY        77388
6  2026  NO INJURY / DRIVE AWAY        18547

#### __Find the day of the week with the highest average crashes per hour__

In [ ]:
# Avg crashes per hour = Total crashes on that weekday / Number of hours observed on that weekday

In [41]:
print(df["CRASH_DAY_OF_WEEK"].value_counts())
print()
print(df["CRASH_HOUR"].value_counts())

CRASH_DAY_OF_WEEK
6    106924
7     97636
5     95453
4     94278
3     92935
2     89408
1     84300
Name: count, dtype: int64

CRASH_HOUR
15    51919
16    50650
17    48389
14    44049
18    39806
13    39555
12    38473
8     34288
11    33557
19    29887
10    29818
9     29310
7     26959
20    24797
21    22047
22    20018
23    18032
0     15481
6     13491
1     13257
2     11107
3      9190
5      8987
4      7867
Name: count, dtype: int64

In [ ]:
query = """
SELECT
    CRASH_DAY_OF_WEEK,
    AVG(crashes_per_hour) AS AVG_CRASHES_PER_HOUR
FROM (
    SELECT
        CRASH_DAY_OF_WEEK,
        CRASH_HOUR,
        COUNT(*) AS crashes_per_hour
    FROM TRAFFIC_CRASHESDATA
    GROUP BY CRASH_DAY_OF_WEEK, CRASH_HOUR
) AS hourly_crashes
GROUP BY
    CRASH_DAY_OF_WEEK
ORDER BY
    AVG_CRASHES_PER_HOUR DESC
"""


#outer query -  Which day has the highest average crashes per hour?
#inner query -  How many crashes happened in each hour of each day?
df20 = pd.read_sql(query,engine)
df20

   CRASH_DAY_OF_WEEK  AVG_CRASHES_PER_HOUR
0                  6             4455.1667
1                  7             4068.1667
2                  5             3977.2083
3                  4             3928.2500
4                  3             3872.2917
5                  2             3725.3333
6                  1             3512.5000

#### __Identify high-risk time slots:__
##### ● Group hours into buckets (Morning, Afternoon, Evening, Night)
##### ● Find which bucket has the highest injury crashes

In [ ]:
## General Understnading 
# - morning 5 am to 11 am
# - Afternoon 12 pm to 3 pm
# - Evening 4 pm to 7 pm
# - Night 8 pm to 4 am

In [59]:
query = """
SELECT
    TIME_FRAME_BUCKET,
    COUNT(*) AS INJURY_CRASH_COUNT
FROM (
    SELECT
        CASE
            WHEN CRASH_HOUR BETWEEN 5 AND 11 THEN 'Morning'
            WHEN CRASH_HOUR BETWEEN 12 AND 15 THEN 'Afternoon'
            WHEN CRASH_HOUR BETWEEN 16 AND 21 THEN 'Evening'
            ELSE 'Night'
        END AS TIME_FRAME_BUCKET
    FROM TRAFFIC_CRASHESDATA
    WHERE INJURIES_TOTAL > 0
) AS time_bucketed_crashes
GROUP BY
    TIME_FRAME_BUCKET
ORDER BY
    INJURY_CRASH_COUNT DESC;
"""

df21 = pd.read_sql(query,engine)
df21

  TIME_FRAME_BUCKET  INJURY_CRASH_COUNT
0           Evening               35680
1           Morning               25465
2         Afternoon               24912
3             Night               18281

#### __Find the top 3 contributing causes for each crash type.__
##### ○  (Use window functions like ROW_NUMBER() or RANK())

In [62]:
query = """
SELECT
    CRASH_TYPE,
    PRIM_CONTRIBUTORY_CAUSE,
    TOTAL_CRASHES
FROM (
    SELECT
        CRASH_TYPE,
        PRIM_CONTRIBUTORY_CAUSE,
        COUNT(*) AS TOTAL_CRASHES,
        ROW_NUMBER() OVER (
            PARTITION BY CRASH_TYPE
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM TRAFFIC_CRASHESDATA
    GROUP BY
        CRASH_TYPE,
        PRIM_CONTRIBUTORY_CAUSE
) AS ranked_causes
WHERE rn <= 3
ORDER BY
    CRASH_TYPE,
    TOTAL_CRASHES DESC;
"""

df22 = pd.read_sql(query, engine)
df22

,CRASH_TYPE,PRIM_CONTRIBUTORY_CAUSE,TOTAL_CRASHES
0,INJURY AND / OR TOW DUE TO CRASH,UNABLE TO DETERMINE,66377
1,INJURY AND / OR TOW DUE TO CRASH,FAILING TO YIELD RIGHT-OF-WAY,31840
2,INJURY AND / OR TOW DUE TO CRASH,FAILING TO REDUCE SPEED TO AVOID CRASH,13224
3,NO INJURY / DRIVE AWAY,UNABLE TO DETERMINE,206391
4,NO INJURY / DRIVE AWAY,FOLLOWING TOO CLOSELY,45964
5,NO INJURY / DRIVE AWAY,FAILING TO YIELD RIGHT-OF-WAY,41573

#### __Identify hotspot zones:__
##### ● Group nearby locations (round latitude & longitude to 2 decimal places)
##### ● Find top 10 zones with highest crashes

In [66]:
query = """
SELECT 
    ROUND(LATITUDE, 2) AS LATITUDE,
    ROUND(LONGITUDE, 2) AS LONGITUDE,
    COUNT(*) AS CRASH_COUNT
FROM traffic_crashesdata
GROUP BY 
    LATITUDE,
    LONGITUDE
ORDER BY 
    CRASH_COUNT DESC
LIMIT 10;
"""

df23 = pd.read_sql(query, engine)
df23

   LATITUDE  LONGITUDE  CRASH_COUNT
0     41.98     -87.91         1247
1     41.90     -87.62          661
2     41.79     -87.58          473
3     41.75     -87.59          469
4     41.72     -87.59          353
5     41.88     -87.62          284
6     41.75     -87.74          264
7     41.90     -87.62          262
8     41.90     -87.62          253
9     41.71     -87.64          244

#### __Calculate the year-over-year growth rate of crashes.__ 
##### ○ (Use LAG() window function)

In [ ]:
### First group by years and total_crash
### Then using LAG window function get the previous year , ordering by years as prev_year_crash
### Now yeay over year growth = (current year - previous year)*100/previous year

In [78]:
query = """
SELECT 
    year,
    total_crashes,
    LAG(total_crashes) OVER (ORDER BY year) AS prev_year_crashes,
    ROUND(
        (total_crashes - LAG(total_crashes) OVER (ORDER BY year)) * 100.0
        / LAG(total_crashes) OVER (ORDER BY year),
        2
    ) AS YEAR_GROWTH_RATE
FROM (
    SELECT 
        year,
        COUNT(*) AS total_crashes
    FROM traffic_crashesdata
    GROUP BY year
) AS yearly_data
ORDER BY year
"""

df24 = pd.read_sql(query, engine)
df24

   year  total_crashes  prev_year_crashes  YEAR_GROWTH_RATE
0  2020          91509                NaN               NaN
1  2021         107937            91509.0             17.95
2  2022         107462           107937.0             -0.44
3  2023         109714           107462.0              2.10
4  2024         110853           109714.0              1.04
5  2025         107965           110853.0             -2.61
6  2026          25494           107965.0            -76.39